include common.mk

all: elfs

#	-ffunction-sections \
#	-fdata-sections \


COPTS += -m68000 \
	 -D R_68K_RELATIVE=22

#	-I_build/headers/include

# stop deleting my dbg elf!
.SECONDARY:

#%.elf.dbg: %.pie.o
#	$(BFDLD) \
#		--gc-sections \
#		--print-gc-sections \
#		--no-dynamic-linker \
#		--hash-style=gnu \
#		--undefined=_start_c \
#		-pie $^ -o $@


#	-Wl,--no-dynamic-linker \

STATICPIE=-fpie -pie -Wl,--no-dynamic-linker

# This reduces the size of the binaries by putting segments
# with different permissions on the same 4K page which you
# might care about if you have an MMU.
COPTS += -Wl,-z,max-page-size=4

%.68000.elf.dbg: %.c
	$(CC) $(COPTS) \
	$(STATICPIE) \
	-o $@ $< -lgcc

%.68000.elf: %.68000.elf.dbg
	$(STRIP) $< -o $@

.PHONY: elfs
elfs: $(addsuffix .68000.elf,$(PROGS))

.PHONY: clean
clean:
	rm -f *.o *.gdb *.68000.elf *.68000.elf.dbg
