include common.mk

COPTS=\
	-ggdb \
	-nostdlib \
	-std=c99 \
	-fpie \
	-flto \
	-Os

%.x86_64.elf.dbg: %.c
	$(CC) $(COPTS) \
	-include $(NOLIBCDIR)/nolibc.h \
	-Wl,--hash-style=gnu \
	-static-pie \
	-D R_AMD64_RELATIVE=8 \
	-o $@ $<

%.x86_64.elf: %.x86_64.elf.dbg
	$(STRIP) $< -o $@

.PHONY: elfs
elfs: $(addsuffix .x86_64.elf,$(PROGS))
