all: init smolsh

# Remove any builtin targets...
.SUFFIXES:

# Make sure we know where to get nolibc
ifndef NOLIBCDIR
$(error Please pass NOLIBCDIR with the path to your copy of nolibc (tools/include/nolibc/ in the linux source))
endif

# Make sure we know where the toolchain is
ifndef CROSS_COMPILE
$(error Please pass CROSS_COMPILE with the prefix of you toolchain)
endif

CC=$(CROSS_COMPILE)gcc
BFDLD=$(CROSS_COMPILE)ld.bfd
STRIP=$(CROSS_COMPILE)strip

COPTS=-m68000 \
	-g \
	-ffunction-sections \
	-fdata-sections \
	-nostdlib \
	-std=c99 \
	-Os \
	-I_build/headers/include

%.o: %.c
	$(CC) $(COPTS) \
	 -include $(NOLIBCDIR)/nolibc.h \
	 -c -o $@ $<

%.pie.o: %.c
	$(CC) $(COPTS) \
	-include $(NOLIBCDIR)/nolibc.h \
	-fpie \
	-c -o $@ $<

init: init.o
	$(CC) $(COPTS) $^ -o $@

smolsh: smolsh.o
	$(CC) $(COPTS) $^ -o $@

# stop deleting my dbg elf!
.SECONDARY:

%.elf.dbg: %.pie.o
	$(BFDLD) \
		--gc-sections \
		--print-gc-sections \
		--no-dynamic-linker \
		--hash-style=gnu \
		-pie $^ -o $@

%.elf: %.elf.dbg
	$(STRIP) $< -o $@

.PHONY: elfs
elfs: init.elf smolsh.elf

.PHONY: clean
clean:
	rm -f init smolsh *.o *.gdb *.elf *.elf.dbg
