include common.mk

all: elfs

# Remove any builtin targets...
.SUFFIXES:

#	-ffunction-sections \
#	-fdata-sections \


COPTS=-m68000 \
	-ggdb \
	-flto \
	-nostdlib \
	-std=c99 \
	-Os \
	-D R_68K_RELATIVE=22 \
	-I_build/headers/include

# stop deleting my dbg elf!
.SECONDARY:

#%.elf.dbg: %.pie.o
#	$(BFDLD) \
#		--gc-sections \
#		--print-gc-sections \
#		--no-dynamic-linker \
#		--hash-style=gnu \
#		--undefined=_start_c \
#		-pie $^ -o $@


#	-Wl,--no-dynamic-linker \


%.68000.elf.dbg: %.c
	$(CC) $(COPTS) \
	-include $(NOLIBCDIR)/nolibc.h \
	-Wl,--hash-style=gnu \
	-Wl,-z,max-page-size=4 \
	-pie -Wl,--no-dynamic-linker \
	-o $@ $< -lgcc

%.68000.elf: %.68000.elf.dbg
	$(STRIP) $< -o $@

.PHONY: elfs
elfs: $(addsuffix .68000.elf,$(PROGS))

.PHONY: clean
clean:
	rm -f init smolsh *.o *.gdb *.68000.elf *.68000.elf.dbg
